# Generated by Django 3.1.5 on 2021-03-01 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deneme', '0002_auto_20210301_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_ekle', models.ImageField(blank=True, null=True, upload_to='urun_resimleri')),
                ('baslik', models.CharField(max_length=50)),
                ('fiyat_ekle', models.SmallIntegerField(max_length=50)),
                ('aciklama', models.CharField(max_length=50)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategoriler', models.ManyToManyField(related_name='urun', to='deneme.KategoriModel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'urunler',
            },
        ),
    ]
