# Generated by Django 3.1.5 on 2021-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0003_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='fiyat_ekle',
            field=models.SmallIntegerField(),
        ),
    ]
