# Generated by Django 3.1.5 on 2021-03-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0005_altkategorimodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altkategorimodel',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
