# Generated by Django 3.1.5 on 2021-03-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0006_auto_20210301_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altkategorimodel',
            name='alt_kategoriler',
        ),
        migrations.AddField(
            model_name='altkategorimodel',
            name='kategoriler',
            field=models.ManyToManyField(related_name='alturun', to='deneme.KategoriModel'),
        ),
    ]
