# Generated by Django 3.1.5 on 2021-03-04 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deneme', '0008_auto_20210301_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=40)),
                ('message', models.TextField(max_length=300)),
                ('mesajgonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'db_table': 'mesaj',
            },
        ),
    ]
