# Generated by Django 3.1.6 on 2021-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0009_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='aciklama',
            field=models.CharField(max_length=350),
        ),
    ]
