# Generated by Django 3.1.6 on 2021-04-10 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deneme', '0010_auto_20210310_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='mesajgonderen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='yazar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YorumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to=settings.AUTH_USER_MODEL)),
                ('yazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='deneme.productmodel')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'yorumlar',
                'db_table': 'yorum',
            },
        ),
    ]
