# Generated by Django 3.1.6 on 2021-05-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0011_auto_20210410_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorummodel',
            name='yazi',
        ),
    ]
