from .kategori import KategoriModel
from .urunler import ProductModel
from .alt_kategori import AltKategoriModel
from .mesaj import MessageModel
from account.models import CustomUserModel
from .urun_yorum import YorumModel
from .customers import Customers
#from .advertise import AdvertiseModel
from .brand import BrandModel
#from .type import TypeModel
#from .property import PropertyModel